apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jp-study-db-pvc
  namespace: jp-study
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi
