apiVersion: v1
kind: Service
metadata:
  name: jp-study
  namespace: jp-study
spec:
  type: LoadBalancer
  selector:
    app: jp-study
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
